### ISSUE TITLE
Feedback on editor UX

### ISSUE THREAD

**Issue by thibaudcolas** [springload/draftail#14]
The UI and UX of the editor (see [demo](https://springload.github.io/draftail/)) as they stand are directly from initial prototypes, which could be refined a bit now that the editor's feature set is better understood. There will be ongoing work on the editor, so the point for now is to make it "good enough" that we don't feel bad about other people to start using it.

Here is a list of specific things to review:

- [ ] Embed block behaviour (see below)
- [ ] Image block behaviour (see below)
- [ ] Undo/redo buttons – or the lack thereof. The default editor in Wagtail has them. Are they worth adding, or should we expect people to know the keyboard shortcuts?

## Embed block behaviour

... or the lack thereof – how the block for embeds has two open/closed states even though there is nothing to act upon in the "open" state. We also do not have a way to edit an existing embed at the moment – instead, the user has to remove it, then add a new one. Would that be worth adding? How?

## Image block behaviour

![draftail-image-block](https://cloud.githubusercontent.com/assets/877585/22058670/754b6fce-dd72-11e6-833d-893651e9a0e0.png)

This is displayed within the editor's UI. There are two states as with the embed block. I'm not sure whether having explicit "Save" and "Cancel" actions in here is good – it dilutes the overall understanding of whether the editor's content is saved or not:

- Within Wagtail, nothing is actually saved until you hit "Save draft" at the bottom of the page
- Outside of Wagtail, there would either be a save mechanism for the whole content as well, or everything would be auto-saved on every change.

Edit: reading time? https://github.com/michael-lynch/reading-time

**Comment by loicteixeira** [comment]
Undo/Redo from the menu of the browser is not propagated to the editor (but is with Halo.js)

**Comment by thibaudcolas** [comment]
```
Undo/Redo: Yes buttons should be here, as a separate group (Google Docs and Word treat them specially).
Embed:
The fact that when opened, it is not clear that you cannot do anything else until you close it. Should be a modal?
Images:
Call to action “save changes” vs “insert image” and ability to edit.
Both:
At the moment, this is a mirror of what Halo.js was doing but given the capabilities of Draft.js, we should probably allow edit.
Delete action?
```

**Comment by katie-day** [comment]
@thibaudcolas for the *image block behaviour* does the save button need to be there? It quite confusing I think there could be a lot of improvement here. 

Some suggestions might be: 
- [ ] Removing the save/cancel buttons (when you click on the image it expands the options, and clicking away from the image collapses those options) 
- [ ] Add space for a caption on the image instead of alt text (which should be added on image upload (this maybe be specific to wagtaildraftail though).
- [ ] Image should respond to user left or right aligning the image. 
- [ ] Remove the dotted line around the image and center it. Make the image it's true size unless it is bigger and in that case make it's width 100%.

**Comment by thibaudcolas** [comment]
Closing this, as those changes are now captured on separate issues that will be easier to prioritise, resource, and deliver 🙂 

See #92 for the image block improvements.
