### ISSUE TITLE
Edit Link button not working in Firefox

### ISSUE THREAD

**Issue by brylie** [springload/draftail#160]
# Current behavior?
When clicking the anchor next to an existing link and then clicking the 'Edit' button, nothing happens. There are some errors in the console, but the code has been minified.

# Steps to reproduce
1. Create or edit a Wagtail page using Firefox
2. Insert a link
3. Click the anchor icon next to the link
4. Click the 'Edit' button in the popup

# Expected behavior
The edit modal should appear, but doesn't

# Environment
Wagtail 2.2
Firefox 61.0.1 (64-bit)
Kubuntu 18.04

**Comment by thibaudcolas** [comment]
Hey @brylie, thanks for reporting this.

I can't reproduce this in my local environment (Firefox 61.0.2 (64-bit), Wagtail 2.2.2, macOS 10.13).

Could you:

1. Re-open this on the Wagtail issue tracker. Any issue with Wagtail should be reported there first (that's where others will look for it).
2. Provide the errors you see in the console, and a more precise step-by-step repro if you think that could help.

Additionally, Wagtail comes with source maps since a recent release (either 2.1 or 2.2, I'm not sure) so if you have the browser developer tools open you should be able to see the error with the un-minified source.
