### ISSUE TITLE
Unable to replicate example without downloading source

### ISSUE THREAD

**Issue by wirelessed** [springload/draftail#175]
Hi 

I'm not sure if I'm doing it wrong, but I'm trying to create an all built-in formats using the example shown in https://github.com/springload/draftail/blob/master/examples/examples.story.js

However, from the .js source given, it seems like most of the components and entities are in separate JS files which has to be downloaded and included in my project. I can't just import everything at once from the draftail `node_modules` folder using `import` statements.

Is there something I'm missing here?

**Comment by thibaudcolas** [comment]
Hey @wirelessed, fair question. "built-in" is a bit misleading, because formats still have to enabled, and also most likely configured as well. For inline styles and block-level formatting, this configuration is really straightforward, and most config options have a default. For example,

```js
import { DraftailEditor, BLOCK_TYPE, INLINE_STYLE } from "draftail";

[...]

<DraftailEditor
    blockTypes={[
      { type: BLOCK_TYPE.HEADER_THREE },
      { type: BLOCK_TYPE.UNORDERED_LIST_ITEM },
    ]}
    inlineStyles={[
      { type: INLINE_STYLE.BOLD },
      { type: INLINE_STYLE.ITALIC },
    ]}
  />
```

^ for those configured formats, there will be a default icon/label and description in the toolbar, as well as a keyboard shortcut, and conversion from HTML in copy/paste. Providing their `type` is enough to get all of this.

Now, for entity (things with data) formats, the editor has *some* built-in support for `LINK` and `IMAGE`. It offers default label/descriptions for the toolbar,  keyboard shortcuts, and HTML copy/paste support. **It doesn't include any UI for the link/image chooser, and how they are displayed in the editor**. This is where "built-in" stops: if you want to use links/images in the editor, you will need to provide the React component to display them, and the one to show a link/image chooser. This is to make it easier to integrate the editor in various types of apps.

I hope it all makes sense, let me know if you have further questions or if you have suggestions to make this clearer in the docs.

**Comment by wirelessed** [comment]
Hi @thibaudcolas 

Thanks for the detailed reply. I understand it now. I was hoping for a full solution out-of-the-box and it seems like there are not many draft-js packages out there as detailed as this.

**Comment by thibaudcolas** [comment]
👍 indeed, there aren't many "fully-featured" Draft.js editors out there. I'd really like for Draftail to be one of those, but this breaks down for links and images where it's much harder than other formats to provide a UI that's both generic enough for a wide variety of integrations, and extensible enough for specific needs.

I'll close this now. If others find it helpful it would obviously be possible to release the image/link implementations from `examples/` to npm (or hopefully something even better), but I have no plans to work on this at the moment.
