### ISSUE TITLE
Module not found: Can't resolve 'draftail/dist/draftail' in '/home/pranav/Desktop/textEditor/text-editor/src'

### ISSUE THREAD

**Issue by pranavpandey1998official** [springload/draftail#204]
it is working if I import 'draftail/dist/draftail.css' but its not black its white in backgound

**Comment by thibaudcolas** [comment]
Hey @pranavpandey1998official 👋 What you’re describing is intended, the black toolbar is only used in the demo styles used in the official docs – otherwise by default the toolbar is black text with a grey background.

Here are the demo styles if you want to reuse them: https://github.com/springload/draftail/blob/b6583bdcc33eb5b115d2ab224afc06270f4a3f2b/examples/main.scss#L29-L37

Please use the issue template (placeholder content in GitHub’s editor) in the future when opening issues.
