### ISSUE TITLE
Add more Markdown-style shortcuts to format content

### ISSUE THREAD

**Issue by tomdyson** [springload/draftail#53]
I love draftail's markdown-style shortcut for starting lists with " - ". Would it be possible to do something similar for code formatting, i.e. start a new block with "```" or inline with "`"?

**Comment by thibaudcolas** [comment]
It's very simple to implement if the shortcut is at the start of the line. (title styles, code block, blockquote). I experimented with it for title levels, but wasn't entirely convinced by the behavior. To revisit!

**Comment by thibaudcolas** [comment]
Here is what this could look like for heading levels:

![markdown-title-shortcuts](https://user-images.githubusercontent.com/877585/32840031-1a57c046-ca1f-11e7-818f-bd5246d53016.gif)

Note that the `#`s before the actual title text are removed from the block when the heading marker is complete (when a space is entered afterwards). Does this look good? I assume we don't want any of the Markdown formatting syntax to end up stored in the text.

The behaviour on undo also has to be defined – whether it preserves the heading marker or not. Preserving:

![markdown-title-undo-1](https://user-images.githubusercontent.com/877585/32840207-b1e4a816-ca1f-11e7-81df-093ebc82a999.gif)

Not preserving:

![markdown-title-undo-2](https://user-images.githubusercontent.com/877585/32840215-b87be0f4-ca1f-11e7-8e1e-2d0e3fc2acfe.gif)

Personally I think "not preserving" would be better, although it means that if people mistype while entering these they'll have to retype from the start of the line.

For code blocks, this is a bit more problematic because the "code block" Markdown marker is one line above the actual formatting. It feels a bit strange to use the triple tick as a "start of the line" marker, although it could still be useful:

![markdown-code-block](https://user-images.githubusercontent.com/877585/32840404-331df5cc-ca20-11e7-894f-21af16c8aef5.gif)

**Comment by tomdyson** [comment]
I love this!

> Does this look good? I assume we don't want any of the Markdown formatting syntax to end up stored in the text.

Yes, I agree it shouldn't end up stored in the text.

> Personally I think "not preserving" would be better

I think I agree with this.

> For code blocks, this is a bit more problematic because the "code block" Markdown marker is one line above the actual formatting. It feels a bit strange to use the triple tick as a "start of the line" marker

This doesn't feel strange in the demo, but I'd like to try it out to confirm the experience.

**Comment by thibaudcolas** [comment]
@tomdyson I've made this available at https://springload.github.io/draftail/ The available markers are: https://github.com/springload/draftail/blob/968fd650a2470b235107a75ca76d79be6d1e9c06/lib/api/constants.js#L215-L228

When trying the code block one you'll most likely run into #104.

**Comment by thibaudcolas** [comment]
@tomdyson I see that Dropbox Paper also uses those shortcuts so I've added all of the ones above, changing the code block one to not need a space (like in Paper). Also added one for blockquotes (`> `), and HRs (`---`, taken from Paper).

Paper also supports Markdown-style syntax for inline styles (bold, italic, code, strikethrough) which it would be nice to implement as well. Finally, it does some character replacements (`---` inside of other text becomes `—`, `--` becomes `–`, smartquotes) which I'm not sure what to think of.

**Comment by davelab6** [comment]
The character replacements are a great idea and I'm hoping you'll adopt them :) 

For advanced users who may want to toggle this off, a toolbar toggle could work, or, simply access to the html source (which I use in a vanilla forums based forum override the typography enhancements when I occasionally don't want them)

**Comment by thibaudcolas** [comment]
@davelab6 thanks for taking the time to comment here. I actually ended up opening a separate issue just for this at https://github.com/springload/draftail/issues/113. If you want to help pushing this forward, it would be nice to get help reviewing what other editors are doing in this area (more info in the issue).

It's harder to build something that's not "one size fits all" (with configuration beyond what's doable in the code), so if that's deemed necessary this is less likely to be implemented sooner rather than later, but I guess we can have that discussion.
